#!/bin/bash
#
# Source this file or set the ANT_ARGS yourself
#

echo "!!!Source this file or set the ANT_ARGS environment variable yourself???"
export ANT_ARGS="-lib contrib/ant-libs/IndentedDefaultLogger.jar -logger com.splunk.IndentedDefaultLogger"
