/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.cloudera.flume.reporter.server.avro;

@SuppressWarnings("all")
public interface AvroFlumeReportServer {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"AvroFlumeReportServer\",\"namespace\":\"com.cloudera.flume.reporter.server.avro\",\"types\":[{\"type\":\"record\",\"name\":\"AvroFlumeReport\",\"fields\":[{\"name\":\"stringMetrics\",\"type\":{\"type\":\"map\",\"values\":\"string\"}},{\"name\":\"longMetrics\",\"type\":{\"type\":\"map\",\"values\":\"long\"}},{\"name\":\"doubleMetrics\",\"type\":{\"type\":\"map\",\"values\":\"double\"}}]}],\"messages\":{\"getAllReports\":{\"request\":[],\"response\":{\"type\":\"map\",\"values\":\"AvroFlumeReport\"}},\"getReportByName\":{\"request\":[{\"name\":\"reportName\",\"type\":\"string\"}],\"response\":\"AvroFlumeReport\"}}}");
  java.util.Map<java.lang.CharSequence,com.cloudera.flume.reporter.server.avro.AvroFlumeReport> getAllReports() throws org.apache.avro.ipc.AvroRemoteException;
  com.cloudera.flume.reporter.server.avro.AvroFlumeReport getReportByName(java.lang.CharSequence reportName) throws org.apache.avro.ipc.AvroRemoteException;
}
